### ISSUE TITLE
Add information for contributors

### ISSUE THREAD

**Issue by mdpiper** [atomneb/AtomNeb-idl#1]
Information should be provided to direct users how to contribute, report problems, or seek help when working with this software.

For example, [astropy](https://github.com/astropy/astropy) has a [CONTRIBUTING.md](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md) file that provides this information. A (far shorter!) version of such a file be appropriate here.

**Comment by danehkar** [comment]
I included [CONTRIBUTING.md](https://github.com/atomneb/AtomNeb-idl/blob/master/CONTRIBUTING.md) in the [AtomNeb-idl](https://github.com/atomneb/AtomNeb-idl) repository that contains some guidelines for contributors.
