### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mdpiper** [atomneb/AtomNeb-idl#2]
Unit tests, written by the developer, are extremely helpful for ensuring that software behaves as a developer intends. (I've caught *so* many defects through unit tests.) Unit tests should be added to this package.

**Comment by mdpiper** [comment]
A suggestion: [mgunit](https://github.com/mgalloy/mgunit) is a mature and widely used unit testing framework for IDL.

**Comment by danehkar** [comment]
@mdpiper I added  [mgunit](https://github.com/mgalloy/mgunit) in the folder  [test_mgunit](https://github.com/atomneb/AtomNeb-idl/tree/master/test_mgunit) for automated tests. 

To test, you can download AtomNeb-idl with its dependencies as follows 

    git clone --recursive https://github.com/atomneb/AtomNeb-idl.git

You need to unpack rc_o_iii_SSB17.fits.tar.gz in ``atomic-data-rc``:

    tar -xvf rc_o_iii_SSB17.fits.tar.gz

To run the test, you need to run the following command:

    idl test_all.pro

There should not be any failure in the ``test-results.html`` file.
