### ISSUE TITLE
Create API documentation

### ISSUE THREAD

**Issue by mdpiper** [atomneb/AtomNeb-idl#4]
Although each function in AtomNeb-idl has a docstring describing its functionality, it's a best practice to create separate API documentation for a package. This makes it easier for developers (and users) to understand what each routine in the package does.

A recommendation: [IDLdoc](https://github.com/mgalloy/idldoc) produces nice API documentation, and it's an accepted standard in the IDL community.

**Comment by mgalloy** [comment]
If you do this for the code in your `examples` directory as well, you can satisfy the documentation of real-world examples requirement as well.

**Comment by danehkar** [comment]
I created API documentation with [IDLdoc](https://github.com/mgalloy/idldoc) and uploaded them to [docs](https://atomneb.github.io/AtomNeb-idl/doc/).
