### ISSUE TITLE
Add note on installing package

### ISSUE THREAD

**Issue by mdpiper** [atomneb/AtomNeb-idl#6]
IDL's path management can be difficult, especially for a newcomer. It would be helpful to add a short note to the README about how to install this package. For example:

### Installation

To install the **AtomNeb** database and API library on your machine, simply add this directory to your IDL path. If you're new to IDL, learn more about path management in [this article](https://www.harrisgeospatial.com/Support/SelfHelpTools/HelpArticles/HelpArticles-Detail/TabId/2718/ArtMID/10220/ArticleID/16156/Quick-tips-for-customizing-your-IDL-program-search-path.aspx) from Harris Geospatial Solutions, or in [this article](http://www.idlcoyote.com/code_tips/installcoyote.php) by David Fanning of the Coyote IDL Library.

**Comment by mgalloy** [comment]
Also, are there requirements for installation? a minimum version of IDL?

**Comment by danehkar** [comment]
I added a [note](https://github.com/atomneb/AtomNeb-idl/commit/f3ce3fb53fb3d741a7fb17e8ce9a7c35f11fddd1) to README on Installation and minimum IDL version.
